colorScheme = "congo"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = false
enableCodeCopy = true
enableImageLazyLoading = true

[header]
  layout = "basic"
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = false

[article]
  showDate = true
  showAuthor = false
  showBreadcrumbs = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = false
  showTableOfContents = false
  showWordCount = false

[list]
  showBreadcrumbs = false
  showSummary = false
  groupByYear = false
